version: '3'

services:
  node:
    image: node:lts-alpine3.16
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./my-app:/my-app
    working_dir: /my-app
    networks:
      - defaults

networks:
  defaults:
